<?php
$slides=$sliders?:[['eyebrow'=>'Pakistan Cambridge School • Hafizabad','title'=>'Where ambition meets education.','subtitle'=>'A modern school community where academic excellence, character, confidence and leadership grow together.','cta_text'=>'Explore Our School','cta_link'=>'#about']];
$multi=count($slides)>1;
$admissionsOpen=setting('admissions_open')==='1';
?>
<section class="hero" data-hero-slider>
    <?php foreach($slides as $si=>$hero): $heroImage=$hero['image']??null; ?>
    <div class="hero-slide<?=$si===0?' active':''?><?=$heroImage?' has-bg-photo':''?>"<?=$heroImage?' style="background-image:url('.e(upload_url($heroImage)).')"':''?> data-slide>
        <div class="hero-overlay"></div>
        <div class="container hero-inner">
            <div class="hero-content" data-reveal>
                <?php if($admissionsOpen):?><div class="hero-badge-row"><span class="hero-badge"><i></i>Admissions Open — 2026–27</span></div><?php endif;?>
                <span class="eyebrow"><i></i><?=e($hero['eyebrow']?:'Pakistan Cambridge School • Hafizabad')?></span>
                <h1><?=e($hero['title'])?></h1>
                <p><?=e($hero['subtitle'])?></p>
                <div class="hero-actions"><a class="btn btn-primary" href="<?=e($hero['cta_link']?:'#admissions')?>"><?=e($hero['cta_text']?:'Explore Our School')?> <span>→</span></a><a class="btn btn-ghost" href="#academics">Discover Academics <span>↓</span></a></div>
            </div>
            <?php if($heroImage):?>
            <div class="hero-visual">
                <div class="hero-visual-card"><img src="<?=e(upload_url($heroImage))?>" alt="<?=e($hero['title'])?>"></div>
                <?php if($statStudents=setting('stat_students')):?><div class="hero-visual-badge"><span class="hero-visual-badge-icon"><?=icon('users',18)?></span><div><strong><?=e($statStudents)?></strong><small>Active Students</small></div></div><?php endif;?>
            </div>
            <?php endif;?>
        </div>
    </div>
    <?php endforeach;?>

    <?php if($multi):?>
    <button class="hero-arrow prev" type="button" aria-label="Previous slide" data-hero-prev><?=icon('arrow',20,'flip')?></button>
    <button class="hero-arrow next" type="button" aria-label="Next slide" data-hero-next><?=icon('arrow',20)?></button>
    <div class="hero-dots" role="tablist" aria-label="Slides">
        <?php foreach($slides as $si=>$s):?><button type="button" class="hero-dot<?=$si===0?' active':''?>" aria-label="Show slide <?=$si+1?>" data-hero-dot="<?=$si?>"></button><?php endforeach;?>
    </div>
    <?php endif;?>

    <div class="hero-bottom"><div class="container quick-links"><a href="#admissions"><span class="quick-icon"><?=icon('send',18)?></span><span><b>Admissions</b><small>Start your journey</small></span></a><a href="#academics"><span class="quick-icon"><?=icon('book',18)?></span><span><b>Academics</b><small>Explore pathways</small></span></a><a href="#life"><span class="quick-icon"><?=icon('award',18)?></span><span><b>Student Life</b><small>Beyond the classroom</small></span></a><a href="#contact"><span class="quick-icon"><?=icon('pin',18)?></span><span><b>Visit Campus</b><small>Come see PCS</small></span></a></div></div>
</section>

<?php
$statStudents=setting('stat_students');$statFaculty=setting('stat_faculty');$statPassRate=setting('stat_pass_rate');$statYears=setting('stat_years');
$hasStats=$statStudents||$statFaculty||$statPassRate||$statYears;
?>
<?php if($hasStats):?>
<section class="stats-strip">
    <div class="container stats-grid" data-reveal-group>
        <?php if($statStudents):?><div class="stat-item"><div class="stat-icon"><?=icon('users',24)?></div><strong><?=e($statStudents)?></strong><span>Students</span></div><?php endif;?>
        <?php if($statFaculty):?><div class="stat-item"><div class="stat-icon"><?=icon('user',24)?></div><strong><?=e($statFaculty)?></strong><span>Faculty Members</span></div><?php endif;?>
        <?php if($statPassRate):?><div class="stat-item"><div class="stat-icon"><?=icon('award',24)?></div><strong><?=e($statPassRate)?></strong><span>Board Pass Rate</span></div><?php endif;?>
        <?php if($statYears):?><div class="stat-item"><div class="stat-icon"><?=icon('clock',24)?></div><strong><?=e($statYears)?></strong><span>Years Serving</span></div><?php endif;?>
    </div>
</section>
<?php endif;?>

<section class="intro section-pad" id="about"><div class="container split-grid"><div class="section-heading" data-reveal><span class="eyebrow dark"><i></i>Welcome to PCS</span><h2>Education that prepares students for <em>what comes next.</em></h2><p>Pakistan Cambridge School Hafizabad is designed around one simple idea: students learn best when high standards are matched with care, confidence and opportunity.</p><a class="text-link" href="#academics">Discover our approach <span>→</span></a></div><div class="intro-panel" data-reveal><div class="panel-number">01</div><h3>More than a classroom</h3><p>We connect strong academics with communication, creativity, discipline, collaboration and real-world problem solving.</p><div class="mini-stats"><div><strong>01</strong><span>Purposeful<br>learning</span></div><div><strong>02</strong><span>Confident<br>communication</span></div><div><strong>03</strong><span>Future-ready<br>skills</span></div></div></div></div></section>

<section class="values section-pad light-section" id="life"><div class="container"><div class="center-heading" data-reveal><span class="eyebrow dark"><i></i>What defines us</span><h2>The PCS <em>difference.</em></h2><p>A balanced school experience built to help every learner discover their strengths and use them well.</p></div><div class="value-grid" data-reveal-group><?php $fallback=[['Academic Excellence','Clear goals, strong foundations and a culture that respects learning.','book'],['Character First','Integrity, discipline, respect and responsibility in everyday school life.','shield'],['Confident Voices','Students are encouraged to ask, present, create, compete and lead.','users'],['Future Ready','Technology, communication and problem-solving skills for a changing world.','award']]; $rows=$values?:array_map(fn($v)=>['title'=>$v[0],'description'=>$v[1],'icon'=>$v[2]],$fallback); foreach($rows as $i=>$v):?><article class="value-card"><div class="value-icon"><?=icon($v['icon']??'book',22)?></div><span class="value-index">0<?=$i+1?></span><h3><?=e($v['title']??'')?></h3><p><?=e($v['description']??'')?></p><a href="#academics">Learn more <span>→</span></a></article><?php endforeach;?></div></div></section>

<section class="academics section-pad" id="academics"><div class="container"><div class="section-row" data-reveal><div><span class="eyebrow dark"><i></i>Academic pathways</span><h2>Learning with <em>purpose.</em></h2></div><p>Structured pathways help students build knowledge step by step while developing the confidence to apply it.</p></div><div class="program-grid" data-reveal-group><?php $fallbackP=[['Early Years','Playgroup • Nursery • Prep','A warm start built around language, numeracy, curiosity and social development.','pencil'],['Primary','Grades I – V','Strong foundations in core subjects, reading, mathematics, science and creative learning.','book'],['Middle School','Grades VI – VIII','Subject-focused learning with technology, communication, sports and student leadership.','mountain'],['Secondary','Grades IX – X','Focused board preparation, practical learning and structured academic support.','flask'],['Cambridge Pathways','Future-focused learning','A pathway for learners aiming for international academic standards and wider opportunities.','award'],['Co-curriculars','Beyond academics','Debate, sports, arts, competitions and clubs that help students discover their strengths.','heart']]; $prows=$programs?:array_map(fn($v)=>['name'=>$v[0],'level'=>$v[1],'description'=>$v[2],'icon'=>$v[3]],$fallbackP); foreach($prows as $i=>$p):?><article class="program-card"><div class="program-top"><span class="program-number">0<?=$i+1?></span><span class="program-icon"><?=icon($p['icon']??'book',22)?></span></div><span class="program-level"><?=e($p['level']??'')?></span><h3><?=e($p['name']??'')?></h3><p><?=e($p['description']??'')?></p><a href="#admissions">Explore pathway <span>→</span></a></article><?php endforeach;?></div></div></section>

<section class="feature-band"><div class="container feature-grid" data-reveal><div><span class="eyebrow light"><i></i>Built for balanced growth</span><h2>Strong academics.<br><em>Stronger character.</em></h2></div><div class="feature-list"><div><b>01</b><span>Student-centred classrooms</span></div><div><b>02</b><span>Clubs, sports & competitions</span></div><div><b>03</b><span>Parent-school partnership</span></div><div><b>04</b><span>Safe, respectful environment</span></div></div></div></section>

<section class="admissions section-pad" id="admissions"><div class="container admission-box" data-reveal><div><span class="eyebrow light"><i></i>Admissions</span><h2>Give your child a place to <em>grow.</em></h2><p>Tell us what you are looking for and our admissions team can guide you through the next step.</p></div><div class="admission-actions"><a class="btn btn-white" href="mailto:<?=e(setting('email','info@example.com'))?>">Request Information <span>→</span></a><a class="btn btn-outline-white" href="#contact">Contact School</a></div></div></section>

<section class="digital-system section-pad light-section"><div class="container"><div class="center-heading" data-reveal><div class="ds-title-row"><span class="ds-heading-icon"><?=icon('monitor',22)?></span><h2>Complete Digital School <em>Management System.</em></h2></div><span class="ds-underline"></span><p>Pakistan Cambridge School Hafizabad is fully digitized — experience modern education management with cutting-edge technology.</p></div><div class="ds-grid" data-reveal-group><div class="ds-card"><div class="ds-icon"><?=icon('chart',22)?></div><div><h3>Online Exam Results</h3><span>Instant results & analysis</span></div></div><div class="ds-card"><div class="ds-icon"><?=icon('userCheck',22)?></div><div><h3>Digital Attendance</h3><span>Real-time tracking</span></div></div><div class="ds-card"><div class="ds-icon"><?=icon('message',22)?></div><div><h3>WhatsApp & SMS</h3><span>Auto alerts to parents</span></div></div><div class="ds-card"><div class="ds-icon"><?=icon('chat',22)?></div><div><h3>Parent Complaints</h3><span>Quick resolution system</span></div></div><div class="ds-card"><div class="ds-icon"><?=icon('wallet',22)?></div><div><h3>Fee History</h3><span>Online fee management</span></div></div><div class="ds-card"><div class="ds-icon"><?=icon('book',22)?></div><div><h3>Digital Diaries</h3><span>Online homework</span></div></div><div class="ds-card"><div class="ds-icon"><?=icon('calendar',22)?></div><div><h3>Smart Timetable</h3><span>Dynamic schedules</span></div></div><div class="ds-card"><div class="ds-icon"><?=icon('clipboard',22)?></div><div><h3>PTM Notes</h3><span>Meeting & feedback</span></div></div></div>
<?php $playUrl=setting('app_play_store_url');$appleUrl=setting('app_app_store_url');?>
<?php if($playUrl||$appleUrl):?><div class="ds-app-banner" data-reveal><div class="ds-app-icon"><?=icon('smartphone',30)?></div><div class="ds-app-text"><h3>Download Our Mobile App</h3><p>Access all school features on your smartphone! Stay connected anytime, anywhere.</p></div><div class="ds-app-badges"><?php if($playUrl):?><a class="ds-badge" href="<?=e($playUrl)?>" target="_blank" rel="noopener"><small>GET IT ON</small><b>Google Play</b></a><?php endif;?><?php if($appleUrl):?><a class="ds-badge" href="<?=e($appleUrl)?>" target="_blank" rel="noopener"><small>Download on the</small><b>App Store</b></a><?php endif;?></div></div><?php endif;?></div></section>

<?php if($leadership):?><section class="leadership-section section-pad light-section"><div class="container"><div class="center-heading" data-reveal><span class="eyebrow dark"><i></i>Our leadership</span><h2>A message from <em>our leaders.</em></h2><p>The people who set the standard at Pakistan Cambridge School Hafizabad.</p></div><div class="leaders-list" data-reveal-group><?php foreach($leadership as $person):?><article class="leader-row"><div class="leader-photo-col"><div class="leader-photo-ring"><?php if(!empty($person['photo'])):?><img src="<?=e(upload_url($person['photo']))?>" alt="<?=e($person['name'])?>"><?php else:?><div class="person-placeholder"><?=icon('user',48)?></div><?php endif;?></div><span class="leader-photo-role"><?=e($person['designation'])?></span><h3><?=e($person['name'])?></h3></div><div class="leader-quote-col"><span class="leader-quote-mark">&ldquo;</span><?php if(!empty($person['message'])):?><div class="leader-message"><?=nl2br(e($person['message']))?></div><?php endif;?><div class="leader-sign"><strong><?=e($person['name'])?></strong><span><?=e($person['designation'])?></span></div></div></article><?php endforeach;?></div></div></section><?php endif;?>

<?php if($faculty):?><section class="people section-pad"><div class="container"><div class="section-row"><div><span class="eyebrow dark"><i></i>Our people</span><h2>Teachers who <em>make a difference.</em></h2></div><p>Great schools are built by educators who combine subject expertise with patience, energy and high expectations.</p></div><div class="people-grid" data-reveal-group><?php foreach($faculty as $person):?><article class="person-card"><?php if(!empty($person['photo'])):?><img src="<?=e(upload_url($person['photo']))?>" alt="<?=e($person['name'])?>"><?php else:?><div class="person-placeholder"><?=icon('user',40)?></div><?php endif;?><div><span><?=e($person['designation'])?></span><h3><?=e($person['name'])?></h3><p><?=e($person['qualification'])?></p></div></article><?php endforeach;?></div></div></section><?php endif;?>

<?php if($news):?><section class="news section-pad light-section" id="news"><div class="container"><div class="section-row"><div><span class="eyebrow dark"><i></i>Latest from PCS</span><h2>News, events & <em>school life.</em></h2></div><p>Stay connected with what is happening across our learning community.</p></div><div class="news-grid" data-reveal-group><?php foreach($news as $item):?><article class="news-card"><?php if(!empty($item['image'])):?><img src="<?=e(upload_url($item['image']))?>" alt="<?=e($item['title'])?>"><?php else:?><div class="news-placeholder"><span><?=e(strtoupper(substr($item['category']??'NEWS',0,1)))?></span></div><?php endif;?><div class="news-body"><span class="news-meta"><?=e(ucfirst($item['category']??'News'))?> • <?=e(format_date($item['published_at']??$item['created_at']??null,'d M Y'))?></span><h3><?=e($item['title'])?></h3><p><?=e(excerpt($item['content']??'',115))?></p><a href="#contact">Read more <span>→</span></a></div></article><?php endforeach;?></div></div></section><?php endif;?>

<?php if($testimonials):?><section class="testimonials section-pad"><div class="container"><div class="center-heading"><span class="eyebrow dark"><i></i>Parent & student voice</span><h2>Small moments. <em>Big impact.</em></h2></div><div class="testimonial-grid" data-reveal-group><?php foreach($testimonials as $item):?><blockquote><div class="quote-mark">“</div><p><?=e($item['quote']??$item['content']??'')?></p><footer><strong><?=e($item['name']??'PCS Community')?></strong><span><?=e($item['designation']??$item['role']??'Parent / Student')?></span></footer></blockquote><?php endforeach;?></div></div></section><?php endif;?>